image: php:7.1.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          #Deps
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpcbf --standard=PSR2 src/
          - vendor/bin/phpunit
  branches:
    pipeline:
      - step:
          caches:
            - composer
          script:
            #Deps
            - apt-get update && apt-get install -y unzip openssh-client
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            #Code Sniffer
            - vendor/bin/phpcbf --standard=PSR2 src/
            #Test
            - vendor/bin/phpunit
            # Upload source code
            - tar czf ../build.tar.gz .
            - scp -r ../build.tar.gz root@$SERVER_HOST:/src
            # Deploy app
            - ssh root@$SERVER_HOST 'cd apps && docker version'

