version: '2'
services:
  nginx:
    extends:
      file: common.yml
      service: nginx
    ports:
      - "8080:80"
    links:
      - php
  php:
    container_name: php
    build: ./image
    working_dir: /var/www/payment-flow
    volumes:
      - ../:/var/www/payment-flow
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - backend
  redis: 
    container_name: redis
    image: redis:alpine
    links:
      - php
    networks:
      - backend

networks:
  backend:
    # Use a custom driver which takes special options
    external: 
      name: backend

