version: '2'
services:
  nginx:
    extends:
      file: common.yml
      service: nginx
    ports:
      - "8080:80"
    links:
      - php
  php:
    extends:
      file: common.yml
      service: php
      
  redis: 
    extends:
      file: common.yml
      service: redis
    links:
      - php


networks:
  backend:
    # Use a custom driver which takes special options
    external: 
      name: backend

