version: '2'
services:
  nginx:
    extends:
      file: common.yml
      service: nginx
    ports:
      - "81:80"
    links:
      - php
    networks:
      - backend
  php:
    extends:
      file: common.yml
      service: php
    networks:
      - backend
      
  redis: 
    extends:
      file: common.yml
      service: redis
    links:
      - php
    networks:
      - backend

networks:
  backend:
    # Use a custom driver which takes special options
    external: 
      name: backend

