version: '2'

services:

  # Web Server
  # Note: The network aliases are for internal naming only. You'll still need
  # add the relevent entries in you /etc/hosts file.
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      # Nginx configuration files
      - "./config/nginx/sites-enabled:/etc/nginx/conf.d"

      # Working folders
      - "../:/var/www/payment-flow"
    labels:
      - com.docker.alias.nginx
    networks:
      common:
        aliases:
          - payment-flow.dev

  # PhpFPM service
  php7fpm:
    container_name: php7
    image: shareableinnovations/php7
    restart: always
    volumes:
      # Composer cache volume
      - "composer-cache:/home/www/.composer/cache"
    volumes_from:
      - nginx
    labels:
      - com.docker.alias.payment-flow
    networks:
      - common

volumes:
  composer-cache:
    driver: local

networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.255.0.0/16
          gateway: 10.255.0.1
