FROM php:7.1-fpm

# Environment Variables
ENV PHP_USER www-data

# Install PHP 7 (ensure noninterative setup)
RUN apt-get update && apt install -y \
    curl \
    libcurl3 \
    libcurl3-dev \
    git \
    zip \
    # PHP7 Libs
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install curl json \
    # X-Debug
    && sed -i '1 a xdebug.remote_autostart=true' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && sed -i '1 a xdebug.remote_mode=req' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && sed -i '1 a xdebug.remote_handler=dbgp' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && sed -i '1 a xdebug.remote_connect_back=1 ' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && sed -i '1 a xdebug.remote_port=9000' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && sed -i '1 a xdebug.remote_enable=1' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    # Give www-data access to the home folder
    && mkdir -p /home/www \
    && chown www-data:staff /home/www \
    # PHP Composer (I think this is not helpful)
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    # cleanup apt and lists
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 9000
EXPOSE 80
